/* Generated By:JavaCC: Do not edit this line. CalculatorTreeConstants.java Version 4.1d1 */
public interface CalculatorTreeConstants
{
  public int JJTERROR_SKIPTO = 0;
  public int JJTEXPRESSION = 1;
  public int JJTVOID = 2;
  public int JJTASSIGN = 3;
  public int JJTADD = 4;
  public int JJTSUB = 5;
  public int JJTMUL = 6;
  public int JJTDIV = 7;
  public int JJTTERM = 8;
  public int JJTRETRIEVE = 9;
  public int JJTMINUS = 10;


  public String[] jjtNodeName = {
    "error_skipto",
    "Expression",
    "void",
    "Assign",
    "Add",
    "Sub",
    "Mul",
    "Div",
    "Term",
    "Retrieve",
    "Minus",
  };
}
/* JavaCC - OriginalChecksum=94d648cfd142c805b9c510bfc469f980 (do not edit this line) */
