/* Generated By:JavaCC: Do not edit this line. CalculatorTreeConstants.java Version 4.1d1 */
public interface CalculatorTreeConstants
{
  public int JJTEXPRESSION = 0;
  public int JJTVOID = 1;
  public int JJTASSIGN = 2;
  public int JJTADD = 3;
  public int JJTSUB = 4;
  public int JJTMUL = 5;
  public int JJTDIV = 6;
  public int JJTTERM = 7;
  public int JJTRETRIEVE = 8;
  public int JJTMINUS = 9;


  public String[] jjtNodeName = {
    "Expression",
    "void",
    "Assign",
    "Add",
    "Sub",
    "Mul",
    "Div",
    "Term",
    "Retrieve",
    "Minus",
  };
}
/* JavaCC - OriginalChecksum=ec82a6a949fc008751e1dd4c1eed0ddd (do not edit this line) */
